### ISSUE TITLE
Use a textual format to store data instead?

### ISSUE THREAD

**Issue by RobertCochran** [JoshuaBrockschmidt/bigram_quoter#5]
I really don't like having data being saved in a binary file format. Binary
files are hard for humans to read and write, and depend on the endianness of
the saving CPU for what the data values actually mean. Any benefits you get
from saving in a binary format (whether 'speed' or 'simplicity') are outweighed
by the fact that **humans are unable to read and write it with standard tools**.

See http://catb.org/esr/writings/taoup/html/ch05s01.html

**Comment by jcbrockschmidt** [comment]
I was going to write out a few counter-points to your proposal. But after reading that article and thinking about it a little more, I'd say the benefits outweigh the repercussion. I'm mostly looking at how a text-based format will make things more flexible. Humans being able to directly read and write to save files isn't of as much concern. Nonetheless, I think I'll get on re-writing the save file format tomorrow.

**Comment by RobertCochran** [comment]
This is my suggestion, so if you need any help on this, yell for me

**Comment by jcbrockschmidt** [comment]
Commit 88ac231485d5c58026dcab9d9ec6290ef51d6d98 fulfills the proposal in this issue. Closing.
